import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x06131b); scene.fog = new THREE.FogExp2(0x06131b, 0.0032);
const camera = new THREE.PerspectiveCamera(62, innerWidth / innerHeight, .1, 1000);
const renderer = new THREE.WebGLRenderer({ antialias:true, powerPreference:'high-performance' });
renderer.setSize(innerWidth, innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.15;
document.querySelector('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x8feeff, 0x091016, 1.8));
const sun = new THREE.DirectionalLight(0x8fcfff, 2); sun.position.set(-60,80,30); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); scene.add(sun);

const track = { R:58, width:17, laps:3 }; const world = new THREE.Group(); scene.add(world);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(650,650), new THREE.MeshStandardMaterial({color:0x07141a, roughness:.95})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; world.add(ground);
function ring(r, tube, color, y=0) { const m=new THREE.Mesh(new THREE.TorusGeometry(r,tube,10,150),new THREE.MeshStandardMaterial({color, roughness:.8, metalness:.1}));m.rotation.x=Math.PI/2;m.position.y=y; world.add(m); return m; }
ring(track.R-track.width/2-.7, .7, 0x26373b,.15); ring(track.R+track.width/2+.7,.7,0x26373b,.15);
ring(track.R-track.width/2, .12, 0x41dce4,.38); ring(track.R+track.width/2,.12,0x41dce4,.38);
const road = new THREE.Mesh(new THREE.RingGeometry(track.R-track.width/2,track.R+track.width/2,160,1),new THREE.MeshStandardMaterial({color:0x172127,roughness:.73,metalness:.1,side:THREE.DoubleSide})); road.rotation.x=-Math.PI/2; road.receiveShadow=true; world.add(road);
const dashMat = new THREE.MeshBasicMaterial({color:0xf4fbdd}); for(let i=0;i<48;i++){const a=i/48*Math.PI*2;const d=new THREE.Mesh(new THREE.BoxGeometry(.36,.05,3),dashMat);d.position.set(Math.sin(a)*track.R,.13,Math.cos(a)*track.R);d.rotation.y=a-Math.PI/2;world.add(d);}
// Compact checkered start line across the width of the road.
for(let row=0;row<4;row++) for(let col=0;col<16;col++){const tile=new THREE.Mesh(new THREE.BoxGeometry(1,.06,1),new THREE.MeshBasicMaterial({color:(row+col)%2?0xeef7f7:0x10171b}));tile.position.set(-1.5+row,.17,track.R-track.width/2+.5+col);world.add(tile);}

// Guardrail posts make speed and track curvature easier to read.
for(let i=0;i<80;i++){const a=i/80*Math.PI*2;for(const side of [-1,1]){const radius=track.R+side*(track.width/2+1);const post=new THREE.Mesh(new THREE.BoxGeometry(.28,1.15,.28),new THREE.MeshStandardMaterial({color:0x54636a,metalness:.7,roughness:.32}));post.position.set(Math.sin(a)*radius,.58,Math.cos(a)*radius);world.add(post);}}
function building(angle, radius, h, w) { const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,w),new THREE.MeshStandardMaterial({color:0x101d25,roughness:.7,metalness:.25,emissive:0x061820,emissiveIntensity:.8})); b.position.set(Math.sin(angle)*radius,h/2,Math.cos(angle)*radius); b.rotation.y=angle; b.castShadow=true;world.add(b); const windowMat=new THREE.MeshBasicMaterial({color:Math.random()>.5?0x38c8df:0xff6e51});for(let y=5;y<h-2;y+=6){const l=new THREE.Mesh(new THREE.BoxGeometry(w+.1,.18,.35),windowMat);l.position.copy(b.position);l.position.y=y;l.rotation.y=angle;world.add(l);} }
for(let i=0;i<44;i++){let a=i/44*Math.PI*2;building(a,92+Math.random()*42,10+Math.random()*53,7+Math.random()*11);}
for(let i=0;i<34;i++){let a=i/34*Math.PI*2; let p=new THREE.PointLight(i%2?0x29e4ff:0xff4f43,4,18);p.position.set(Math.sin(a)*(track.R+(i%2?11:-11)),5,Math.cos(a)*(track.R+(i%2?11:-11)));scene.add(p);}

const starPositions=[];for(let i=0;i<700;i++){const radius=120+Math.random()*260,angle=Math.random()*Math.PI*2;starPositions.push(Math.sin(angle)*radius,35+Math.random()*150,Math.cos(angle)*radius);}
const stars=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xa9e8ff,size:.55,sizeAttenuation:true,transparent:true,opacity:.8}));stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));scene.add(stars);

function makeCar(color, accent=0xffffff) { const g=new THREE.Group(); const bodyMat=new THREE.MeshStandardMaterial({color,metalness:.62,roughness:.23}); const body=new THREE.Mesh(new THREE.BoxGeometry(3.1,.65,5.7),bodyMat);body.position.y=.72;body.castShadow=true;g.add(body);const hood=new THREE.Mesh(new THREE.BoxGeometry(2.8,.32,2.1),bodyMat);hood.position.set(0,1.05,-1.2);hood.rotation.x=-.11;g.add(hood);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.25,.7,2.2),new THREE.MeshStandardMaterial({color:0x09131b,metalness:.8,roughness:.08}));cabin.position.set(0,1.37,.55);cabin.rotation.x=.11;g.add(cabin);for(const x of [-.9,.9]){const headlight=new THREE.Mesh(new THREE.BoxGeometry(.55,.18,.12),new THREE.MeshBasicMaterial({color:0xc8faff}));headlight.position.set(x,.82,-2.9);g.add(headlight);}const rear=new THREE.Mesh(new THREE.BoxGeometry(2.7,.13,.15),new THREE.MeshBasicMaterial({color:0xff2e32}));rear.position.set(0,.82,2.9);g.add(rear);const underglow=new THREE.Mesh(new THREE.PlaneGeometry(2.7,4.5),new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:.2,depthWrite:false,side:THREE.DoubleSide}));underglow.rotation.x=-Math.PI/2;underglow.position.y=.13;g.add(underglow);const wheelMat=new THREE.MeshStandardMaterial({color:0x050607,roughness:.55}); for(const x of [-1.56,1.56])for(const z of [-1.8,1.8]){const wh=new THREE.Mesh(new THREE.CylinderGeometry(.52,.52,.36,14),wheelMat);wh.rotation.z=Math.PI/2;wh.position.set(x,.48,z);g.add(wh);} return g; }
const player = { name:'YOU', color:0x13c8e2, progress:.015, speed:0, targetSpeed:0, lane:0, steerVisual:0, car:makeCar(0x13c8e2,0xd7ffff), lap:1, lastProgress:.015, boost:100, finish:false }; world.add(player.car);
const names=['VOLT','NOVA','RUSH']; const colors=[0xff5146,0xf4be35,0xa45eff]; const racers=[player]; names.forEach((name,i)=>{const r={name,color:colors[i],progress:.035+(i*.018),speed:20+i*1.8,lane:(i-1)*3.4,car:makeCar(colors[i]),lap:1,lastProgress:0};world.add(r.car);racers.push(r);});
function place(r) { const a=r.progress*Math.PI*2; const radius=track.R+r.lane; r.car.position.set(Math.sin(a)*radius,.05,Math.cos(a)*radius); r.car.rotation.y=a-Math.PI/2+(r.steerVisual||0); }
racers.forEach(place); camera.position.set(0, 14, 82); camera.lookAt(0, 0, 20);
const keys={}; addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true; if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const el=id=>document.getElementById(id), clock=new THREE.Clock(), cameraLook=new THREE.Vector3(0,1,58); let started=false, startedAt=0, raceOver=false;
function ordinal(n){return n===1?'ST':n===2?'ND':n===3?'RD':'TH';} function rank(){return [...racers].sort((a,b)=>(b.lap-1+b.progress)-(a.lap-1+a.progress));}
function updateHUD(now){const ordered=rank(), pos=ordered.indexOf(player)+1;el('speed').textContent=String(Math.round(player.speed*4.2)).padStart(3,'0');el('gear').textContent=player.speed<3?'N':Math.min(6,Math.ceil(player.speed/10));el('position').innerHTML=`${pos}<span>${ordinal(pos)}</span>`;el('lap').innerHTML=`${Math.min(player.lap,3)} <span>/ 3</span>`;el('boostFill').style.width=player.boost+'%';el('boostNum').textContent=Math.round(player.boost)+'%';const t=now-startedAt;el('time').textContent=`${String(Math.floor(t/60000)).padStart(2,'0')}:${String(Math.floor(t/1000)%60).padStart(2,'0')}.${String(Math.floor(t%1000)).padStart(3,'0')}`;el('leaderboard').innerHTML=ordered.map((r,i)=>`<div class="${r===player?'you':''}"><span>${i+1}. ${r.name}</span><b>${r.lap>3?'FIN':r.lap+'/3'}</b></div>`).join('');}
function finish(){raceOver=true;const p=rank().indexOf(player)+1;el('finish').classList.remove('hidden');el('finish').innerHTML=`<div>${p===1?'VICTORY!':'RACE COMPLETE'}</div><p>YOU FINISHED ${p}${ordinal(p)} PLACE</p><button onclick="location.reload()">RACE AGAIN</button>`;}
function countDown(){const c=el('countdown');let n=3;c.textContent=n;const timer=setInterval(()=>{n--;c.textContent=n>0?n:'GO!';if(n<0){clearInterval(timer);c.textContent='';started=true;startedAt=performance.now();}},760);}
el('startButton').onclick=()=>{el('startScreen').classList.add('gone');countDown();};
function animate(now){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(started&&!raceOver){const accelerating=keys.w||keys.arrowup, braking=keys.s||keys.arrowdown, boost=(keys.shift&&accelerating&&player.boost>0);player.targetSpeed=accelerating?(boost?39:28):0;if(braking)player.targetSpeed=-9;player.speed+= (player.targetSpeed-player.speed)*((accelerating||braking)?.9:.55)*dt*2.4; if(!accelerating&&!braking)player.speed*=Math.pow(.985,dt*60);if(boost){player.boost=Math.max(0,player.boost-25*dt);}else player.boost=Math.min(100,player.boost+5.5*dt);const steer=(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0);player.lane=THREE.MathUtils.clamp(player.lane+steer*dt*13,-6.8,6.8);player.steerVisual+=(steer*-.13-player.steerVisual)*Math.min(1,dt*7);player.progress+=player.speed*dt/(Math.PI*2*(track.R+player.lane));if(player.progress>=1){player.progress-=1;player.lap++;if(player.lap>track.laps)finish();}else if(player.progress<0){if(player.lap===1){player.progress=0;player.speed=0;}else{player.progress+=1;player.lap--;}}for(let i=1;i<racers.length;i++){let r=racers[i];r.speed=20+i*1.7+Math.sin(now*.0007+i*5)*2;r.lane+=(Math.sin(now*.0004+i*4)*3-r.lane)*dt*.45;r.progress+=r.speed*dt/(Math.PI*2*(track.R+r.lane));if(r.progress>=1){r.progress-=1;r.lap++;}place(r);}place(player);const a=player.progress*Math.PI*2;const radial=new THREE.Vector3(Math.sin(a),0,Math.cos(a)),tangent=new THREE.Vector3(Math.cos(a),0,-Math.sin(a));const desired=player.car.position.clone().add(radial.clone().multiplyScalar(10)).add(tangent.clone().multiplyScalar(-19)).add(new THREE.Vector3(0,8.5,0));camera.position.lerp(desired,1-Math.pow(.002,dt));const targetLook=player.car.position.clone().add(tangent.multiplyScalar(10)).add(new THREE.Vector3(0,1.2,0));cameraLook.lerp(targetLook,1-Math.pow(.00005,dt));camera.lookAt(cameraLook);camera.fov+=( (boost?69:62)-camera.fov)*Math.min(1,dt*4);camera.updateProjectionMatrix();updateHUD(now);}renderer.render(scene,camera);}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}); animate();
